ayurcare/urls.py
from django.contrib import admin
from django.urls import path,include
from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    path('admin/', admin.site.urls), 
    path('',include('web.urls',namespace='web')),
    path('official/',include('official.urls',namespace='official')),

    path('tinymce/', include('tinymce.urls')),

]+ static(settings.STATIC_URL, document_root=settings.STATIC_ROOT) + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)
admin.site.site_header = "Ayurcare Administration"
admin.site.site_title = "Ayurcare Admin Portal"
admin.site.index_title = "Welcome to Ayurcare Admin Portal"

official/urls.py
from django.urls import path
from official.views import *
 
app_name = 'official'  

urlpatterns = [
    path('',addDistrict,name="addDistrict"),

    path('addBranch/',addBranch,name="addBranch"),
    path('log_in',log_in,name="log_in"),
    path('logout/', logout, name='logout'),
    path('addDoctor/',addDoctor,name="addDoctor"),
    path('addSchedule/',addSchedule,name="addSchedule"),
    path('addGallery/',addGallery,name="addGallery"),
    path('addTestimonial/',addTestimonial,name="addTestimonial"),
    
    path('delet/<str:id>',delet,name="delet"),
    path('deletbranch/<str:id>',deletbranch,name="deletbranch"),
    path('deletdoct/<str:id>',deletdoct,name="deletdoct"),
    path('deleteGallery/<str:id>',deleteGallery,name="deletdoct"),
    path('deletsched/<str:id>',deletsched,name="deletsched"),
    path('deleteTestimonial/<str:id>',deleteTestimonial,name="deleteTestimonial"),
    
]

web/urls.py
from django.urls import path
from . import views

app_name = 'web'

urlpatterns = [
    path('', views.index,name="index"),
    path('about/',views.about,name="about"),
    path('branch/',views.branch,name="branch"),
    path('contact/',views.contact,name="contact"),
    path('doctors/',views.doctors,name="doctors"),
    path('galleries/',views.galleries,name="gallery"),
    path('products/',views.products,name="products"), 
    path('book/<int:id>',views.book,name="book"), 

    path('branchmark/',views.branchmark,name="branchmark"),
    path('districtsr/',views.districtsr,name="districtsr"),

    path('branchbook/<int:id>/',views.branchbook,name="branchbook"),
    path('email/',views.email,name="email"),

]

official/forms.py
from django import forms
from django.contrib.auth.base_user import AbstractBaseUser
from django.db import models
from django.db.models import fields

from web.models import Gallery, Testimonial
from .models import Branch,Doctor,Schedule,DistrictMap
from django.forms.widgets import SelectMultiple, TextInput, Textarea, EmailInput, CheckboxInput,URLInput, Select, NumberInput, RadioSelect, FileInput,TimeInput
from django.contrib.admin import widgets 
from django.contrib.auth.models import User


class DistrictMapForm(forms.ModelForm):
    class Meta:
        model = DistrictMap
        fields = '__all__'
        widgets = {
            'name': TextInput(attrs={'class': 'form-control', 'placeholder': 'District Name','id':'name','name':'name'}),
            'latitude': TextInput(attrs={'class': 'form-control lat', 'placeholder': 'District latitude','id':'latitude','name':'latitude'}),
            'longitude': TextInput(attrs={'class': 'form-control lon', 'placeholder': 'District longitude','id':'longitude','name':'longitude'}),
        }

class BranchForm(forms.ModelForm):
    class Meta:
        model = Branch
        fields = '__all__'
        widgets = {
            'name': TextInput(attrs={'class': 'form-control', 'placeholder': 'Branch Name','id':'name','name':'name'}),
            'title': TextInput(attrs={'class': 'form-control ', 'placeholder': 'Branch Title','id':'title','name':'title'}),
            'phone': TextInput(attrs={'class': 'form-control', 'placeholder': 'Branch Phone','id':'phone','name':'phone'}),
            'location': TextInput(attrs={'class': 'form-control', 'placeholder': 'Branch Location','id':'location','name':'location'}),
            'latitude': TextInput(attrs={'class': 'form-control lat', 'placeholder': 'Branch latitude','id':'latitude','name':'latitude'}),
            'longitude': TextInput(attrs={'class': 'form-control lon', 'placeholder': 'Branch longitude','id':'longitude','name':'longitude'}),

        }

class DoctorForm(forms.ModelForm):
    class Meta:
        model = Doctor
        fields = '__all__'
        widgets = {
            'register_number': NumberInput(attrs={'class': 'form-control', 'placeholder': 'Register Number','id':'registernumber','name':'register_number'}),
            'name': TextInput(attrs={'class': 'form-control ', 'placeholder': 'Name','id':'name','name':'name'}),
            'image': FileInput(attrs={'class': 'form-control', 'placeholder': 'image','id':'image','name':'image'}),
            'qualification': TextInput(attrs={'class': 'form-control lat', 'placeholder': 'Designation','id':'qualification','name':'qualification'}),
            'inHomeScreen':CheckboxInput(attrs={'class': 'form-check-input','id':'inHomeScreen','name':'inHomeScreen','checked':'true'})
            
        }


class GalleryForm(forms.ModelForm):
    class Meta:
        model = Gallery
        fields = '__all__'
        widgets = {
            'image': FileInput(attrs={'class': 'form-control', 'placeholder': 'image','id':'image','name':'image'}),
          
            
        }

class TestimonialForm(forms.ModelForm):
    class Meta:
        model = Testimonial
        fields = '__all__'
        widgets = {
            'image': FileInput(attrs={'class': 'form-control', 'placeholder': 'image','id':'image','name':'image'}),
            'name': TextInput(attrs={'class': 'form-control ', 'placeholder': 'Name','id':'name','name':'name'}),
            'text': TextInput(attrs={'class': 'form-control ', 'placeholder': 'text','id':'text','name':'text'}),
          
            
        }
class ScheduleForm(forms.ModelForm): 
    class Meta:
        model = Schedule
        fields = '__all__'
        widgets = {
            'treatment': TextInput(attrs={'class': 'form-control', 'placeholder': 'treatment','id':'treatment','name':'treatment'}),
            'branch': Select(attrs={'class': 'form-control ','id':'branid','name':'branch'}),
            'doctor': Select(attrs={'class': 'form-control','id':'doctid','name':'doctor'}),
            'day': TextInput(attrs={'class': 'form-control', 'placeholder': 'day','id':'day','name':'day'}),
            'start_time': TimeInput(attrs={'class': 'form-control','type':'time','id':'starttime','name':'starttime'}),
            'end_time': TimeInput(attrs={'class': 'form-control','type':'time','id':'endtime','name':'endtime'}),

        }

official/views.py
from django.db import models
from django.shortcuts import render,get_object_or_404,redirect
from django.http import HttpResponse
from django.urls import reverse
from django.contrib.auth.decorators import login_required
import json
from official.forms import BranchForm,DoctorForm,ScheduleForm,DistrictMapForm,GalleryForm,TestimonialForm
from .models import Branch, DistrictMap, Doctor, Schedule 
from web.models import Gallery,Testimonial
from django.contrib.auth import authenticate, login
from django.contrib.auth import get_user_model
from django.contrib.auth import login as auth_login
from django.contrib import messages 
from django.contrib import auth




def log_in(request):
    if request.user.is_authenticated:
        return redirect ('official:addDistrict')
    else:
        username = request.POST.get("username")
        password = request.POST.get("password")
        if username is not None and password is not None:
            user=authenticate(username=username, password=password)     
            if user is not None:
                login(request, user)
                return redirect("/official/")
            else:   
                messages.error(request, "Invalid Details") 
        else:
            messages.error(request,None)

    return render (request, 'official/login.html')  


def logout(request):
    auth.logout(request)
    return redirect('official:log_in')


@login_required(login_url='official:log_in')
def addDistrict(request):
    districtlist = DistrictMap.objects.all()
    districtform = DistrictMapForm(request.POST or None)

    if request.method == 'POST':
        if request.POST.get('id') != '0':
            editDistrictMap = DistrictMap.objects.get(id =request.POST.get('id'))
            editDistrictMap.name = request.POST.get('name')
            editDistrictMap.latitude = request.POST.get('latitude')
            editDistrictMap.longitude = request.POST.get('longitude')
            editDistrictMap.save()
            response_data = {
                        "status" : "true",                 
                        "message" : "District Edited"
                    }
            return HttpResponse(json.dumps(response_data), content_type='application/javascript')

        else: 
            if districtform.is_valid():
                districtform.save()          
                response_data = {
                        "status" : "true",
                        "title" : "Successfully Added",
                        "message" : "District Added"
                    }
            else:
                response_data = {
                    "status" : "false",
                    "title" : "Form validation error",
                }
            return HttpResponse(json.dumps(response_data), content_type='application/javascript')
    else:
        context = {
                "is_addDistrict" : True,
                "districtform":districtform,
                "districtlist":districtlist,
        }
    return render(request, 'official/addDistrict.html',context)


@login_required(login_url='official:log_in')
def addBranch(request):
    branchlist = Branch.objects.all()
    branchform = BranchForm(request.POST or None)

    if request.method == 'POST':
        if request.POST.get('id') != '0':
            editBranch = Branch.objects.get(id =request.POST.get('id'))
            editBranch.name = request.POST.get('name')
            editBranch.title = request.POST.get('title')
            editBranch.phone = request.POST.get('phone')
            editBranch.location = request.POST.get('location')
            editBranch.latitude = request.POST.get('latitude')
            editBranch.longitude = request.POST.get('longitude')
            editBranch.save()
            response_data = {
                        "status" : "true",
                        "message" : "Branch Edited"
                    }
            return HttpResponse(json.dumps(response_data), content_type='application/javascript')
        else:
            if branchform.is_valid():
                branchform.save()          
                response_data = {
                        "status" : "true",
                        "title" : "Successfully Added",
                        "message" : "Branch Added"
                    }
            else:
                response_data = {
                    "status" : "false",
                    "title" : "Form validation error",
                }
            return HttpResponse(json.dumps(response_data), content_type='application/javascript')
    else:
        context = {
            "is_addBranch" : True,
            "branchform":branchform,
            "branchlist":branchlist,
        }

    return render(request, 'official/addBranch.html',context)


@login_required(login_url='official:log_in')
def addDoctor(request):
    doctorlist = Doctor.objects.all()
    doctorform = DoctorForm(request.POST,request.FILES)

    if request.method == 'POST':
        if request.POST.get('id') != '0':
            editDoctor = Doctor.objects.get(id =request.POST.get('id'))
            editDoctor.register_number = request.POST.get('register_number')
            editDoctor.name = request.POST.get('name')
            if request.FILES.get('image'):
                editDoctor.image = request.FILES.get('image')
            editDoctor.qualification = request.POST.get('qualification')
            editDoctor.save()
            response_data = {
                        "status" : "true",                 
                        "message" : "Doctor Edited"
                    }
            return HttpResponse(json.dumps(response_data), content_type='application/javascript')
        else:

            if doctorform.is_valid():
                doctorform.save()          
                response_data = {
                    "status" : "true",
                    "title" : "Successfully Added",
                    "message" : "Doctor Added"
                }
            else:
                response_data = {
                    "status" : "false",
                }
            return HttpResponse(json.dumps(response_data), content_type='application/javascript')
    else:
        context = {
            "is_addDoctor" : True,
            "doctorform":doctorform,
            "doctorlist":doctorlist,
        }
    return render(request, 'official/addDoctor.html',context)



@login_required(login_url='official:log_in')
def addGallery(request):
    galleryItems = Gallery.objects.all()
    galleryForm = GalleryForm(request.POST,request.FILES)

    if request.method == 'POST':
        if galleryForm.is_valid():
            galleryForm.save()          
            response_data = {
                "status" : "true",
                "title" : "Successfully Added",
                "message" : "Gallery Added"
            }
        else:
            response_data = {
                "status" : "false",
            }
        return HttpResponse(json.dumps(response_data), content_type='application/javascript')
    else:
        context = {
            "is_gallery" : True,
            "galleryForm":galleryForm,
            "galleryItems":galleryItems,
        }
    return render(request, 'official/gallery.html',context)

@login_required(login_url='official:log_in')
def addTestimonial(request):
    TestimonialItems = Testimonial.objects.all()
    testimonialForm = TestimonialForm(request.POST,request.FILES)

    if request.method == 'POST':
        if testimonialForm.is_valid():
            testimonialForm.save()          
            response_data = {
                "status" : "true",
                "title" : "Successfully Added",
                "message" : "Testimonial Added"
            }
        else:
            response_data = {
                "status" : "false",
            }
        return HttpResponse(json.dumps(response_data), content_type='application/javascript')
    else:
        context = {
            "is_testimonial" : True,
            "testimonialForm":testimonialForm,
            "TestimonialItems":TestimonialItems,
        }
    return render(request, 'official/testimonial.html',context)


@login_required(login_url='official:log_in')
def addSchedule(request):
    schedulelist = Schedule.objects.all()
    scheduleform = ScheduleForm(request.POST or None)

    if request.method == 'POST':
        if request.POST.get('id') != '0':
            editSchedule = Schedule.objects.get(id =request.POST.get('id'))
            editSchedule.treatment = request.POST.get('treatment')
            editSchedule.branch.id = int(request.POST.get('branch'))
            editSchedule.doctor.id = int(request.POST.get('doctor'))
            editSchedule.day = request.POST.get('day')
            editSchedule.start_time = request.POST.get('start_time')
            editSchedule.end_time = request.POST.get('end_time')
            editSchedule.save()
            response_data = {
                        "status" : "true",
                        "message" : "Schedule Edited"
                    }
            return HttpResponse(json.dumps(response_data), content_type='application/javascript')
        else:
            if scheduleform.is_valid():
                scheduleform.save()          
                response_data = {
                        "status" : "true",
                        "title" : "Successfully Added",
                        "message" : "Schedule Added"
                    }
            else:
                response_data = {
                    "status" : "false",
                    "title" : "Form validation error",
                }
            return HttpResponse(json.dumps(response_data), content_type='application/javascript')
    else:
        context = {
            "is_addSchedule" : True,
            "scheduleform":scheduleform,
            "schedulelist":schedulelist,
        }
    
    return render(request, 'official/addSchedule.html',context)


def delet(request,id):

templates/official/addDistrict.html
{% extends 'official/base.html' %}
{% load static %}
{% block content %}

<link href="https://cdnjs.cloudflare.com/ajax/libs/twitter-bootstrap/4.5.2/css/bootstrap.css" rel="stylesheet">
<link href="https://cdn.datatables.net/1.11.3/css/dataTables.bootstrap4.min.css" rel="stylesheet">



<div class="container">
  <h3 style="color: #3f993c;" class="text-center">List <span onclick="formclr()" class="adnew"><a href="#contact"><i class="bi bi-plus-circle mr-2"></i>Add New</a></span> </h3>
  <div class="row">


    <table id="example" class="table table-striped table-bordered" style="width:100%">
      <thead>
        <tr>
          <th>District</th>
          <th>latitude</th>
          <th>longitude</th>
          <th>Action</th>
        </tr>
      </thead>
      <tbody>
        {% for districtlist in districtlist %}
        <tr>
          <td>{{districtlist.name}}</td>
          <td>{{districtlist.latitude}}</td>
          <td>{{districtlist.longitude}}</td>
          <td>
            <div class="acti" id="{{districtlist.id}}">
              <a href="#contact"><i onclick="editt('{{districtlist.id}}',this)" class="bi bi-pencil-square"></i></a>
             <a> <i onclick="delet('{{districtlist.id}}')" class="bi bi-trash ms-3 ng-red"></i> </a>
            </div>

          </td>
        </tr>
        {% endfor %}
      </tbody>
      <tfoot>
        <tr>
          <th>District</th>
          <th>latitude</th>
          <th>longitude</th>
          <th>Action</th>
        </tr>
      </tfoot>
    </table>

  </div>
</div>

<!-- ======= Contact Section ======= -->
<section id="contact" class="contact">
  <div class="container">

    <h3 id="titedit" class="text-center">Add District</h3>


    <div class="row justify-content-center" data-aos="fade-up" data-aos-delay="300">
      <div class="col-xl-9 col-lg-12 mt-4">
        <form action="" method="POST" class="ajax reload" id="resform">
          {% csrf_token %}
          <input type="hidden"  value="0" id="disID" name="id"> 
          <div class="row mt-3">
            <div class="col-md-12 form-group">

              {{districtform.name}}

            </div>
          </div>


          <div class="form-group mt-3  text-center">
            <button type="button" class="btn btn-primar" id="btn-geolocation">Find current location</button>
          </div>

          <br>

          <div class="row">
            <div class="col-md-6 form-group">
              {{districtform.latitude}}
            </div>
            <div class="col-md-6 form-group mt-3 mt-md-0">
              {{districtform.longitude}}
            </div>
          </div>
          <div class="my-3">

          </div>
          <div class="text-center">
            <button class="btn btn-danger" type="submit">Submit</button>
          </div>
        </form>
      </div>

    </div>

  </div>
</section><!-- End Contact Section -->



{% endblock %}


{% block javascript %}
<script src="https://code.jquery.com/jquery-3.5.1.js"></script>
<script src="https://cdn.datatables.net/1.11.3/js/jquery.dataTables.min.js"></script>
<script src="https://cdn.datatables.net/1.11.3/js/dataTables.bootstrap4.min.js"></script>

<script>
  $(document).ready(function () {
    $('#example').DataTable();
  });
</script>


<script src="https://unpkg.com/sweetalert/dist/sweetalert.min.js"></script>
<script>

  function formclr() {
    $("#titedit").html("Add District");
    $("#resform").trigger("reset")
  }

  function delet(ids) {
    swal({
      title: "Are you sure?",
      text: "Once deleted, you will not be able to recover this Data!",
      icon: "warning",
      buttons: true,
      dangerMode: true,
    })
      .then((willDelete) => {
        if (willDelete) {
          $.ajax({
            url: "delet/" + ids,
            type: "GET",
            success: function (response) {
              $('#' + ids).closest('tr').remove()
            }

          })
        } else {
          swal("Your imaginary file is safe!");
        }
      });
  }

  function editt(id,thisProp) {
    $("#titedit").html("Edit District"+ "<span onclick='formclr()' class='adnew'><a href='#contact'><i class='bi bi-plus-circle mr-2'></i>Add New</a></span>");
    var name = $(thisProp).closest('tr').find("td:eq(0)").html();
    var latitude = $(thisProp).closest('tr').find("td:eq(1)").html();
    var longitude = $(thisProp).closest('tr').find("td:eq(2)").html();
    

    $('#name').val(name)
    $('#latitude').val(latitude)
    $('#longitude').val(longitude)
    $('#disID').val(id)
    

    
  }



</script>
{% endblock %}

templates/official/base.html
{% load static %}


<!DOCTYPE html>
<html lang="en">

<head>
  <meta charset="utf-8">
  <meta content="width=device-width, initial-scale=1.0" name="viewport">

  <title>OFFICIAL - AYUCARE </title>
  <meta content="" name="description">
  <meta content="" name="keywords">

  <!-- Favicons -->
  <link href="{% static 'official/assets/img/favv.png' %}" rel="icon">
  <link href="{% static 'official/assets/img/favv.png' %}" rel="apple-touch-icon">

  <!-- Google Fonts -->
  <link
    href="https://fonts.googleapis.com/css?family=Open+Sans:300,300i,400,400i,600,600i,700,700i|Raleway:300,300i,400,400i,500,500i,600,600i,700,700i|Poppins:300,300i,400,400i,500,500i,600,600i,700,700i"
    rel="stylesheet">

  <!-- Vendor CSS Files -->
  <link href="{% static 'official/assets/vendor/aos/aos.css' %}" rel="stylesheet">
  <link href="{% static 'official/assets/vendor/bootstrap/css/bootstrap.min.css' %}" rel="stylesheet">
  <link href="{% static 'official/assets/vendor/bootstrap-icons/bootstrap-icons.css' %}" rel="stylesheet">
  <link href="{% static 'official/assets/vendor/boxicons/css/boxicons.min.css' %}" rel="stylesheet">
  <link href="{% static 'official/assets/vendor/glightbox/css/glightbox.min.css' %}" rel="stylesheet">
  <link href="{% static 'official/assets/vendor/swiper/swiper-bundle.min.css' %}" rel="stylesheet">

  <!-- AYUCARE Main CSS File -->
  <link href="{% static 'official/assets/css/style.css' %}" rel="stylesheet">


</head>

<body>

  <!-- ======= Top Bar ======= -->
  <section id="topbar" class="d-flex align-items-center">
    <div class="container d-flex justify-content-center justify-content-md-between">

      

      <div class="contact-info d-flex align-items-center">
        <i class="bi bi-envelope d-flex align-items-center"><a
            href="mailto:contact@example.com">info@ayucare.com</a></i>
        <i class="bi bi-phone d-flex align-items-center ms-4"><span>+91 9876543210</span></i>
      </div>

      <div class="cta d-none d-md-flex align-items-center">
        <a href="#" class="scrollto d-none">Get Started</a>
      </div>
    </div>
  </section>

  <!-- ======= Header ======= -->
  <header id="header" class="d-flex align-items-center">
    <div class="container d-flex align-items-center justify-content-between">

      <div class="logo">
        <h1><a href="{% url 'official:log_in' %}">AYUCARE OFFICIAL</a></h1>
        <!-- Uncomment below if you prefer to use an image logo -->
        <!-- <a href="#"><img src="{% static 'official/assets/img/logo.png' %}" alt="" class="img-fluid"></a>-->
      </div>

      <nav id="navbar" class="navbar"> 
        <ul>
          <li><a class="nav-link scrollto {% if is_addDistrict %}active{% endif %}" href="{% url 'official:addDistrict' %}">Add District</a></li>
          <li><a class="nav-link scrollto {% if is_addBranch %}active{% endif %}" href="{% url 'official:addBranch' %}">Add Branch</a></li>
          <li><a class="nav-link scrollto {% if is_addDoctor %}active{% endif %}" href="{% url 'official:addDoctor' %}">Add Doctor</a></li>
          <li><a class="nav-link scrollto {% if is_addSchedule %}active{% endif %}" href="{% url 'official:addSchedule' %}">Add Schedule</a></li>
          <li><a class="nav-link scrollto {% if is_gallery %}active{% endif %}" href="{% url 'official:addGallery' %}">Add Gallery</a></li>
          <li><a class="nav-link scrollto {% if is_testimonial %}active{% endif %}" href="{% url 'official:addTestimonial' %}">Testimonial</a></li>
          

          {% if user.is_authenticated %}
          <li><a class="nav-link scrollto" href="{% url 'official:logout' %}">Logout</a></li>
          {% endif %}

        </ul>
        <i class="bi bi-list mobile-nav-toggle"></i>
      </nav><!-- .navbar -->

    </div>
  </header><!-- End Header -->



  <main id="main">



{% block content %}

{% endblock %}


    

  </main><!-- End #main -->

  <!-- ======= Footer ======= -->
  <footer id="footer">

    <!-- <div class="footer-top">
      <div class="container">
        <div class="row">

          <div class="col-lg-3 col-md-6 footer-contact">
            <h3>AYUCARE</h3>
            <p>
               
              <strong>Phone : </strong>9876543210<br>
              <strong>Email : </strong>info@ayucare.com<br>
            </p>
          </div>

          <div class="col-lg-2 col-md-6 footer-links">
            <h4>Useful Links</h4>
            <ul>
              <li><i class="bx bx-chevron-right"></i> <a href="#">Home</a></li>
              <li><i class="bx bx-chevron-right"></i> <a href="#">About us</a></li>
              <li><i class="bx bx-chevron-right"></i> <a href="#">Services</a></li>
              <li><i class="bx bx-chevron-right"></i> <a href="#">Terms of service</a></li>
              <li><i class="bx bx-chevron-right"></i> <a href="#">Privacy policy</a></li>
            </ul>
          </div>

          <div class="col-lg-3 col-md-6 footer-links">
            <h4>Our Services</h4>
            <ul>
              <li><i class="bx bx-chevron-right"></i> <a href="#">Web Design</a></li>
              <li><i class="bx bx-chevron-right"></i> <a href="#">Web Development</a></li>
              <li><i class="bx bx-chevron-right"></i> <a href="#">Product Management</a></li>
              <li><i class="bx bx-chevron-right"></i> <a href="#">Marketing</a></li>
              <li><i class="bx bx-chevron-right"></i> <a href="#">Graphic Design</a></li>
            </ul>
          </div>

          <div class="col-lg-4 col-md-6 footer-newsletter">
            <h4>Join Our Newsletter</h4>
            <p>Tamen quem nulla quae legam multos aute sint culpa legam noster magna</p>
            <form action="" method="post">
              <input type="email" name="email"><input type="submit" value="Subscribe">
            </form>
          </div>

        </div>
      </div>
    </div> -->

    <div class="container d-lg-flex py-4">

      <div class="me-lg-auto text-center text-lg-start">
        <div class="copyright">
          &copy; Copyright <strong><span>AYUCARE</span></strong>. All Rights Reserved
        </div>
        <div class="credits">
          Designed by <a href="https://gedexo.com/">Gedexo</a>
        </div>
      </div>
      <div class="social-links text-center text-lg-right pt-3 pt-lg-0">
        <a href="#" class="twitter"><i class="bx bxl-twitter"></i></a>
        <a href="#" class="facebook"><i class="bx bxl-facebook"></i></a>
        <a href="#" class="instagram"><i class="bx bxl-instagram"></i></a>
        <a href="#" class="google-plus"><i class="bx bxl-skype"></i></a>
        <a href="#" class="linkedin"><i class="bx bxl-linkedin"></i></a>
      </div>
    </div>
  </footer>
  <!-- End Footer -->

  <a href="#" class="back-to-top d-flex align-items-center justify-content-center"><i
      class="bi bi-arrow-up-short"></i></a>

  <!-- Vendor JS Files -->
  <script src="https://cdnjs.cloudflare.com/ajax/libs/jquery/3.5.0/jquery.min.js"
    integrity="sha256-xNzN2a4ltkB44Mc/Jz3pT4iU1cmeR0FkXs4pru/JxaQ=" crossorigin="anonymous"></script>
  <script src="https://cdn.jsdelivr.net/npm/sweetalert2@9.15.3/dist/sweetalert2.all.min.js"></script>
  <script src="{% static 'official/assets/vendor/aos/aos.js' %}"></script>
  <script src="{% static 'official/assets/vendor/bootstrap/js/bootstrap.bundle.min.js' %}"></script>
  <script src="{% static 'official/assets/vendor/glightbox/js/glightbox.min.js' %}"></script>
  <script src="{% static 'official/assets/vendor/isotope-layout/isotope.pkgd.min.js' %}"></script>
  <script src="{% static 'official/assets/vendor/swiper/swiper-bundle.min.js' %}"></script>


  <script>
    $(document).on('submit', 'form.ajax', function (e) {
      e.preventDefault();
      var $this = $(this);
      var data = new FormData(this);
      var action_url = $this.attr('action');
      var reset = $this.hasClass('reset');
      var reload = $this.hasClass('reload');
      var redirect = $this.hasClass('redirect');
      var redirect_url = $this.attr('data-redirect');

      $.ajax({
        url: action_url,
        type: 'POST',
        data: data,
        cache: false,
        contentType: false,
        processData: false,
        dataType: "json",

        success: function (data) {

          var status = data.status;
          var title = data.title;
          var message = data.message;
          var pk = data.pk;

          if (status == "true") {
            if (title) {
              title = title;
            } else {
              title = "Success";
            }

            Swal.fire({
              title: title,
              html: message,
              icon: 'success',
            }).then(function () {
              if (redirect) {
                window.location.href = redirect_url;
              }
              if (reload) {
                window.location.reload();
              }
              if (reset) {
                window.location.reset();
              }
            });

          } else {
            if (title) {
              title = title;
            } else {
              title = "An Error Occurred";
            }
            Swal.fire({
              title: title,
              html: message,
              icon: "error"
            });

          }
        },
        error: function (data) {
          var title = "An error occurred";
          var message = "something went wrong";
          Swal.fire({
            title: title,
            html: message,
            icon: "error"
          });
        }
      });
    });
  </script>
  <!-- AYUCARE Main JS File -->
  <script src="{% static 'official/assets/js/main.js' %}"></script>


  <script>

$(window).ready(function() {
    $("#btn-geolocation").click(findLocation);
  });

  function findLocation() {
    navigator.geolocation.getCurrentPosition(getCoords, handleErrors);
  }

  function getCoords(position) {
    $(".lat").val(position.coords.latitude);
    $(".lon").val(position.coords.longitude);
  }

  function handleErrors(error) {
    switch (error.code) {
      case error.PERMISSION_DENIED:
        alert("You need to share your geolocation data.");
        break;

      case error.POSITION_UNAVAILABLE:
        alert("Current position not available.");
        break;

      case error.TIMEOUT:
        alert("Retrieving position timed out.");
        break;

      default:
        alert("Error");
        break;
    }
  }

  </script>

{% block javascript %}

{% endblock %}



</body>

</html>