ayurcare/urls.py
from django.contrib import admin
from django.urls import path,include
from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    path('admin/', admin.site.urls), 
    path('',include('web.urls',namespace='web')),
    path('official/',include('official.urls',namespace='official')),

    path('tinymce/', include('tinymce.urls')),

]+ static(settings.STATIC_URL, document_root=settings.STATIC_ROOT) + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)
admin.site.site_header = "Ayurcare Administration"
admin.site.site_title = "Ayurcare Admin Portal"
admin.site.index_title = "Welcome to Ayurcare Admin Portal"

web/urls.py
from django.urls import path
from . import views

app_name = 'web'

urlpatterns = [
    path('', views.index,name="index"),
    path('about/',views.about,name="about"),
    path('branch/',views.branch,name="branch"),
    path('contact/',views.contact,name="contact"),
    path('doctors/',views.doctors,name="doctors"),
    path('galleries/',views.galleries,name="gallery"),
    path('products/',views.products,name="products"), 
    path('book/<int:id>',views.book,name="book"), 

    path('branchmark/',views.branchmark,name="branchmark"),
    path('districtsr/',views.districtsr,name="districtsr"),

    path('branchbook/<int:id>/',views.branchbook,name="branchbook"),
    path('email/',views.email,name="email"),

]

templates/web/base.html
<html>
<head>
    {% load static %}
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
    <link rel="preconnect" href="https://fonts.googleapis.com">
    <link rel="preconnect" href="https://fonts.gstatic.com" crossorigin>

    <link href="https://fonts.googleapis.com/css2?family=Mulish:wght@200;300;400;500;700;800;900;1000&display=swap"
        rel="stylesheet">
    <link rel="stylesheet"
        href="{% static 'web/css/fonts,_icomoon,_style.css+css,_owl.carousel.min.css+css,_bootstrap.min.css+css,_style.css.pagespeed.cc.11YcxEXwqA.css' %}" />
    <link rel="stylesheet" href="{% static 'web/css/style.css' %}">
    <link rel="stylesheet" href="{% static 'web/css/responsive.css' %}">
    <link rel="stylesheet" href="{% static 'web/css/icofont/icofont.min.css' %}">

    <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/OwlCarousel2/2.3.4/assets/owl.carousel.min.css">
    <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/OwlCarousel2/2.3.4/assets/owl.theme.default.css">


    <link href="{% static 'web/images/favv.png' %}" rel="icon">
    <title>AYUCARE</title>
</head>

{% include 'web/partials/header.html' %}
{% block content %}

{% endblock %}

{% include 'web/partials/footer.html' %}




<script
    src="{% static 'web/js/popper.min.js' %}"></script>
<script src="https://code.iconify.design/2/2.0.3/iconify.min.js "></script>
<script src="https://ajax.googleapis.com/ajax/libs/jquery/3.5.1/jquery.min.js "></script>
<script src="{% static 'web/js/click.js' %}" ></script>
<script src="{% static 'web/js/main.js' %}"></script>

<script src="https://cdn.jsdelivr.net/npm/sweetalert2@9.15.3/dist/sweetalert2.all.min.js"></script>
<script>
    $(document).on('submit', 'form.ajax', function (e) {
        e.preventDefault();
        var $this = $(this);
        var data = new FormData(this);
        var action_url = $this.attr('action');
        var reset = $this.hasClass('reset');
        var reload = $this.hasClass('reload');
        var redirect = $this.hasClass('redirect');
        var redirect_url = $this.attr('data-redirect');

        $.ajax({
            url: action_url,
            type: 'POST',
            data: data,
            cache: false,
            contentType: false,
            processData: false,
            dataType: "json",

            success: function (data) {

                var status = data.status;
                var title = data.title;
                var message = data.message;
                var pk = data.pk;

                if (status == "true") {
                    if (title) {
                        title = title;
                    } else {
                        title = "Success";
                    }

                    Swal.fire({
                        title: title,
                        html: message,
                        icon: 'success',
                    }).then(function () {
                        if (redirect) {
                            window.location.href = redirect_url;
                        }
                        if (reload) {
                            window.location.reload();
                        }
                        if (reset) {
                            window.location.reset();
                        }
                    });

                } else {
                    if (title) {
                        title = title;
                    } else {
                        title = "An Error Occurred";
                    }
                    Swal.fire({
                        title: title,
                        html: message,
                        icon: "error"
                    });

                }
            },
            error: function (data) {
                var title = "An error occurred";
                var message = "something went wrong";
                Swal.fire({
                    title: title,
                    html: message,
                    icon: "error"
                });
            }
        });
    });
</script>

{% block javascript %}

{% endblock %}

</body>

</html>

templates/web/branch.html
{% extends 'web/base.html' %}
{% load static %}
{% block content %}



<style>
    .gm-style .gm-style-iw-c {
        position: absolute;
        box-sizing: border-box;
        overflow: hidden;
        top: 0;
        left: 0;
        transform: translate3d(-50%, -100%, 0);
        background-color: white;
        border-radius: 8px;
        padding: 12px;
        box-shadow: 0 2px 7px 1px rgb(0 0 0 / 30%);
        display: none;

    }

    .gm-style .gm-style-iw-t::after {
        background: linear-gradient(45deg, rgba(255, 255, 255, 1) 50%, rgba(255, 255, 255, 0) 51%, rgba(255, 255, 255, 0) 100%);
        box-shadow: -2px 2px 2px 0 rgb(178 178 178 / 40%);
        content: "";
        height: 15px;
        left: 0;
        position: absolute;
        top: 0;
        transform: translate(-50%, -50%) rotate(-45deg);
        width: 15px;
        display: none;
    }
</style>

<div class="container-fluid branchh">
    <div class="row text-center">
        <div class="col-lg-12 col-12 p-0 position-relative doct">

            {% include 'web/map.html' %}

        </div>


        <div class="col-lg-3 col-md-6 col-sm-12 col-12 position-absolute searc ">
            <h3>Search in District</h3>
            <div class="input-group">

                <input id="auto" type="text" class="form-control form-controll" placeholder="District"
                    aria-label="Locate us" aria-describedby="basic-addon2">

                <div class="input-group-append">
                    <span class="input-group-text input-group-textt"
                        style="background-color:#3f993c; border-color: #3f993c;" id="basic-addon2"><span
                            class="iconify input-group-textt" data-icon="fluent:search-28-filled"></span></span>
                </div>
            </div>


        </div>
        <div class="col-lg-3 col-md-6 col-sm-12 col-12 position-absolute searcc branch ">
            <h4>Branch Details</h4>


            <div class="row pl-5">
                <div class="col-lg-2 col-md-2 col-sm-2 col-2 p-0"><i class="icofont-building"></i></div>
                <div class="col-lg-10 col-md-10 col-sm-10 col-10 p-0">
                    <p id="branchname" style="color: white; text-align: left;"> <span
                            style="font-weight: 500;">Maliyekkal
                            Medicals,</span> <br>Kondotty,<br>Kerala - 673 678</p>
                </div>
            </div>
            <div class="row pl-5">
                <div class="col-lg-2 col-md-2 col-sm-2 col-2 p-0"><i class="icofont-email"></i></div>
                <div class="col-lg-10 col-md-10 col-sm-10 col-10 p-0">
                    <p id="branchphone" style="color: white; text-align: left;"> <span style="font-weight: 500;"> <a
                                href="mailto:booking@ayucare.com">booking@ayucare.com</a> </span>
                </div>
            </div>
            <div class="row pl-5">
                <div class="col-lg-2 col-md-2 col-sm-2 col-2 p-0"><i class="icofont-ui-call"></i></div>
                <div class="col-lg-10 col-md-10 col-sm-10 col-10 p-0">
                    <p id="branchlocation" style="color: white; text-align: left;"> <span style="font-weight: 500;"> <a
                                href="tel:+919846272655">(+91) 9846 272 655</a> </span>
                </div>
            </div>
            <p id=""></p>

            <a id="brannid"> <button style="background-color: #3f993c !important;" class="read check appoii mt-1">Book
                    Appoinment</button> </a>




        </div>


    </div>
</div>




<div class="container-fluid care ">
    <div class="row ">
        <div class="col-lg-12 col-md-12 col-sm-12 col-12 p-0 ">
            <img class="loc-sm " style="position: relative; " src="{% static 'web/images/suscribe.png' %} "
                width="100% " alt=" ">
            <div class="col-lg-6 col-md-12 col-sm-12 col-12 locate locates ">
                <p>Stay in Touch with us</p>
                <p class="mb-3 ">Know more about <span class="ayt ">Ayucare</span> </p>


                <form action="{% url 'web:email' %}" method="POST" class="ajax reload">
                    {% csrf_token %}
                    {{ email_form.email }}
                    <button type="submit" class="btn read mt-2">Subscribe</button>

                </form>

            </div>
        </div>
    </div>
</div>
{% endblock %}

{% block javascript %}


<script src="https://code.jquery.com/jquery-1.12.4.js">
</script>
<script src="https://code.jquery.com/ui/1.12.1/jquery-ui.js">
</script>


<script type="text/javascript">


    $(document).ready(function () {

        loadmap('11.2697233','76.2467868',7)
        var itemsID = [
        ];
        var items = [
        ];
        
        $.ajax({
            url: "/districtsr/",
            type: "GET",
            success: function (response) {
                data = [response]

                $.each(response, function (i, item) {
                    items.push(item.name)
                    itemsID.push([item.id,item.name,item.latitude,item.longitude])
                    
                });
                
                

                $("#auto").autocomplete({
                    source: items 
                });
            }

        })

        $("#auto").keyup(function () {
            if ($.inArray($("#auto").val(), items) != -1) {
                var lat=''
                var log=''
                $.each(itemsID, function (i, item) {
                    
                   if(item[1]==$("#auto").val()){
                    lat=item[2]
                    log=item[3]
                   }
                   
               });
                loadmap(lat,log,10)
            }
        })



    })
</script>

<!-- <script>
    $(document).ready(function () {
        // array of items.
        var items = [
            
        ];
        // jQuery inbuild function
        $("#auto").autocomplete({
            source: items // list of items.
        });
    })
</script> -->



<script type="text/javascript">
    function loadmap(lat,log,zoom) {
        
        $.ajax({
            url: "/branchmark/",
            type: "GET",
            success: function (response) {
                data = [response]
                var locations = [

                ];
                $.each(response, function (i, item) {
                    locations.push([item.name, item.latitude, item.longitude, item.id, item.phone, item.location])


                });

                
                var map = new google.maps.Map(document.getElementById('map'), {
                    zoom: zoom,

                    center: new google.maps.LatLng(lat, log),

                    // center: new google.maps.LatLng(-33.92, 151.25),
                    mapTypeId: google.maps.MapTypeId.ROADMAP
                });

                var infowindow = new google.maps.InfoWindow();

                var marker, i;

                for (i = 0; i < locations.length; i++) {
                    marker = new google.maps.Marker({
                        position: new google.maps.LatLng(locations[i][1], locations[i][2]),
                        map: map
                    });

                    google.maps.event.addListener(marker, 'click', (function (marker, i) {

                        return function () {
                            infowindow.setContent(locations[i][3] + branchclk(locations[i][3]));
                            infowindow.open(map, marker);
                        }
                    })(marker, i));


                    function branchclk(ids) {

                        var datas = locations.find(x => x[3] === ids);

                        $('#branchname').html(datas[0])
                        $('#branchphone').html(datas[4])
                        $('#branchlocation').html(datas[5])

                        $("#brannid").click(function () {
                            location.href = '/branchbook/' + ids + '/'

                        })

                        $('.branch').show();


                    }

                    $(document).mouseup(function (e) {
                        var container = $(".branch");
                        // if the target of the click isn't the container nor a descendant of the container
                        if (!container.is(e.target) && container.has(e.target).length === 0) {
                            container.hide();
                        }
                    });
                }
            }

        })
    }
</script>

<script>
    $('.branch').hide();
</script>






{% endblock %}

templates/web/gallery.html
{% extends 'web/base.html' %}
{% load static %}
{% block content %}

<div class="container-fluid mb-4">
    <div class="row">
        <div class="col-lg-12 col-md-12 col-sm-12 p-0">
            <img class="title-fit" width="100%" src="{% static 'web/images/gallerybg.png' %}" style="position: relative;" alt="">
            <div class="col-lg-6 col-md-6 col-sm-8 col-8 titile">
                <h1 style="color: rgb(255, 255, 255);">Gallery <span style="color: #3f993c;">AYUCARE</span></h1>
            </div>
        </div>
    </div>
</div>


<div class="container mb-5 mt-5">
    <div class="row">
        {% for gallery in galleries %}
        <div class="col-lg-4 col-md-4 col-sm-6 col-6 pb-4 ">
            <img src="{{gallery.image.url}}" width="100%" alt="missing image">
        </div>
        {% endfor %}
        
    </div>
</div>

<div class="container-fluid care ">
    <div class="row ">
        <div class="col-lg-12 col-md-12 col-sm-12 col-12 p-0 ">
            <img class="loc-sm " style="position: relative; " src="{% static 'web/images/suscribe.png' %} "
                width="100% " alt=" ">
            <div class="col-lg-6 col-md-12 col-sm-12 col-12 locate locates ">
                <p>Stay in Touch with us</p>
                <p class="mb-3 ">Know more about <span class="ayt ">Ayucare</span> </p>


                <form action="{% url 'web:email' %}" method="POST" class="ajax reload">
                    {% csrf_token %}
                    {{ email_form.email }}
                    <button type="submit" class="btn read mt-2">Subscribe</button>

                </form>

            </div>
        </div>
    </div>
</div>
{% endblock %}

templates/web/map.html
  <script src="https://maps.google.com/maps/api/js?key=AIzaSyDnZM2wkGhX5O2CBKveClAikks8NI-WvPc" 
          type="text/javascript"></script>

  <div id="map" style="width: 100%; height: 400px;"></div>

templates/web/products.html
{% extends 'web/base.html' %}
{% load static %}
{% block content %}

<div class="container-fluid mb-4">
    <div class="row">
        <div class="col-lg-12 col-md-12 col-sm-12 p-0">
            <img class="title-fit" width="100%" src="{% static 'web/images/prodbg.png' %}" style="position: relative;" alt="">
            <div class="col-lg-6 col-md-6 col-sm-8 col-8 titile">
                <h1 style="color: rgb(255, 255, 255);">Product <span style="color: #3f993c;">AYUCARE</span></h1>
            </div>
        </div>
    </div>
</div>



<div class="vector text-center mt-5 mb-5">
    <svg class="svg-15" width="20" height="20" viewBox="0 0 35 35" fill="none" xmlns="http://www.w3.org/2000/svg">
        <path
            d="M26.5417 10.9375C26.25 7.875 26.1042 4.8125 26.3958 1.60417C24.6458 3.9375 22.6042 5.97917 20.5625 8.02083C19.3958 5.39583 18.2292 2.77083 17.5 0C16.7708 2.77083 15.6042 5.39583 14.4375 8.02083C12.3958 6.125 10.3542 3.9375 8.60417 1.60417C8.89583 4.8125 8.75 7.875 8.45833 10.9375C5.6875 9.91667 2.625 8.75 0 7.29167C3.9375 14.2917 5.54167 22.6042 7.875 28C9.1875 32.0833 12.9792 35 17.5 35C22.0208 35 25.9583 32.0833 27.2708 27.8542C29.4583 22.6042 31.0625 14.2917 35 7.29167C32.375 8.75 29.3125 9.91667 26.5417 10.9375ZM24.7917 5.6875C24.7917 7.72917 24.7917 9.625 24.9375 11.375C25.375 11.2292 23.7708 11.8125 22.75 12.1042C22.3125 11.2292 21.875 10.3542 21.2917 9.33333C22.4583 8.3125 23.625 7.14583 24.7917 5.6875ZM10.0625 11.5208C10.2083 9.77083 10.2083 7.875 10.2083 5.6875C11.375 7 12.5417 8.3125 13.7083 9.47917C13.2708 10.3542 12.8333 11.375 12.25 12.25C11.0833 11.8125 9.625 11.375 10.0625 11.5208ZM5.10417 12.3958C7.29167 13.2708 9.33333 14 11.0833 14.5833C9.91667 16.7708 8.89583 18.9583 8.16667 20.8542C7.4375 18.6667 6.41667 15.6042 5.10417 12.3958ZM17.5 32.0833C13.4167 32.0833 10.2083 28.875 10.2083 24.7917C10.2083 20.7083 13.125 17.5 17.5 7.29167C21.875 17.5 24.7917 20.7083 24.7917 24.7917C24.7917 28.875 21.5833 32.0833 17.5 32.0833ZM26.8333 20.8542C26.1042 18.9583 25.0833 16.9167 23.9167 14.5833C25.6667 14 27.7083 13.2708 29.8958 12.3958C28.5833 15.6042 27.5625 18.5208 26.8333 20.8542Z"
            fill="#3f993c" />
    </svg>
    <svg class="ml-4 mr-4 svg-20" width="35" height="35" viewBox="0 0 35 35" fill="none"
        xmlns="http://www.w3.org/2000/svg">
        <path
            d="M26.5417 10.9375C26.25 7.875 26.1042 4.8125 26.3958 1.60417C24.6458 3.9375 22.6042 5.97917 20.5625 8.02083C19.3958 5.39583 18.2292 2.77083 17.5 0C16.7708 2.77083 15.6042 5.39583 14.4375 8.02083C12.3958 6.125 10.3542 3.9375 8.60417 1.60417C8.89583 4.8125 8.75 7.875 8.45833 10.9375C5.6875 9.91667 2.625 8.75 0 7.29167C3.9375 14.2917 5.54167 22.6042 7.875 28C9.1875 32.0833 12.9792 35 17.5 35C22.0208 35 25.9583 32.0833 27.2708 27.8542C29.4583 22.6042 31.0625 14.2917 35 7.29167C32.375 8.75 29.3125 9.91667 26.5417 10.9375ZM24.7917 5.6875C24.7917 7.72917 24.7917 9.625 24.9375 11.375C25.375 11.2292 23.7708 11.8125 22.75 12.1042C22.3125 11.2292 21.875 10.3542 21.2917 9.33333C22.4583 8.3125 23.625 7.14583 24.7917 5.6875ZM10.0625 11.5208C10.2083 9.77083 10.2083 7.875 10.2083 5.6875C11.375 7 12.5417 8.3125 13.7083 9.47917C13.2708 10.3542 12.8333 11.375 12.25 12.25C11.0833 11.8125 9.625 11.375 10.0625 11.5208ZM5.10417 12.3958C7.29167 13.2708 9.33333 14 11.0833 14.5833C9.91667 16.7708 8.89583 18.9583 8.16667 20.8542C7.4375 18.6667 6.41667 15.6042 5.10417 12.3958ZM17.5 32.0833C13.4167 32.0833 10.2083 28.875 10.2083 24.7917C10.2083 20.7083 13.125 17.5 17.5 7.29167C21.875 17.5 24.7917 20.7083 24.7917 24.7917C24.7917 28.875 21.5833 32.0833 17.5 32.0833ZM26.8333 20.8542C26.1042 18.9583 25.0833 16.9167 23.9167 14.5833C25.6667 14 27.7083 13.2708 29.8958 12.3958C28.5833 15.6042 27.5625 18.5208 26.8333 20.8542Z"
            fill="#3f993c" />
    </svg>
    <svg class="svg-15" width="20" height="20" viewBox="0 0 35 35" fill="none" xmlns="http://www.w3.org/2000/svg">
        <path
            d="M26.5417 10.9375C26.25 7.875 26.1042 4.8125 26.3958 1.60417C24.6458 3.9375 22.6042 5.97917 20.5625 8.02083C19.3958 5.39583 18.2292 2.77083 17.5 0C16.7708 2.77083 15.6042 5.39583 14.4375 8.02083C12.3958 6.125 10.3542 3.9375 8.60417 1.60417C8.89583 4.8125 8.75 7.875 8.45833 10.9375C5.6875 9.91667 2.625 8.75 0 7.29167C3.9375 14.2917 5.54167 22.6042 7.875 28C9.1875 32.0833 12.9792 35 17.5 35C22.0208 35 25.9583 32.0833 27.2708 27.8542C29.4583 22.6042 31.0625 14.2917 35 7.29167C32.375 8.75 29.3125 9.91667 26.5417 10.9375ZM24.7917 5.6875C24.7917 7.72917 24.7917 9.625 24.9375 11.375C25.375 11.2292 23.7708 11.8125 22.75 12.1042C22.3125 11.2292 21.875 10.3542 21.2917 9.33333C22.4583 8.3125 23.625 7.14583 24.7917 5.6875ZM10.0625 11.5208C10.2083 9.77083 10.2083 7.875 10.2083 5.6875C11.375 7 12.5417 8.3125 13.7083 9.47917C13.2708 10.3542 12.8333 11.375 12.25 12.25C11.0833 11.8125 9.625 11.375 10.0625 11.5208ZM5.10417 12.3958C7.29167 13.2708 9.33333 14 11.0833 14.5833C9.91667 16.7708 8.89583 18.9583 8.16667 20.8542C7.4375 18.6667 6.41667 15.6042 5.10417 12.3958ZM17.5 32.0833C13.4167 32.0833 10.2083 28.875 10.2083 24.7917C10.2083 20.7083 13.125 17.5 17.5 7.29167C21.875 17.5 24.7917 20.7083 24.7917 24.7917C24.7917 28.875 21.5833 32.0833 17.5 32.0833ZM26.8333 20.8542C26.1042 18.9583 25.0833 16.9167 23.9167 14.5833C25.6667 14 27.7083 13.2708 29.8958 12.3958C28.5833 15.6042 27.5625 18.5208 26.8333 20.8542Z"
            fill="#3f993c" />
    </svg>
</div>

<div class="text-center">
    <p class="overall">About our Product</p>
    <p class="overall font-20">Ayucare  is the treatment method introduced to cure ailments through Ayurvedic methods by
        adding the elements of Arka Chikitsa. The treatment uses the natural herbs to make the medicines and as a result
        this treatment is free from side effects. Ayurvedic medicines are known as Medicine with Side benefits. The
        medicine is the most potent form of Ayurvedic medicine and is prepared through the process of distillation. The
        extracted product after distillation is called arka.</p>
</div>

<div class="container">
    <div class="row">
        <div class="col-lg-12 col-12">
            <img class="pro" width="100%" src="{% static 'web/images/protemp.png' %}" alt="">
        </div>
    </div>
</div>

<p class="overall font-20">The medicine is safe for diabetics patients to consume. We provide proper consultation and
    treatment from qualified and dedicated doctors. The Kashaya and Massage, two major factors of traditional ayurvedic
    treatment, are not practiced in AYUCARE. We always keep up our excellence in caring for curing the patient.</p>


<div class="container-fluid mt-5">
    <div class="row">
        <div class="col-lg-7 col-md-12 col-sm-12 col-12 p-0 position-relative">
            <img class="proimag" src="{% static 'web/images/lert.png' %}" width="100%" alt="">
        </div>

        <div class="col-lg-7 col-md-10 col-sm-10 col-10 position-absolute ayurrr prod">

            <p>Ayucare  is binded with ayurveda and like its ancient tradition natural herbs are used for medicinal
                purposes. The medicine is manufactured with keen observation and vigilance through distillation. The
                natural herbs in the exact proportion are distilled and extracted to get the “Arka” . Arka medicines are
                the most potent form of Ayurvedic medicine and are more palatable and devoid of colour and smell. </p>
            <p>Self home therapy or DIY (Do It Yourself) products are also recommended as a part of the treatment. The
                medicine from natural herbs is very easy and safe to consume. Ayurvedic medicine is considered as the
                medicine with side benefits because unlike other medicines these medicines are free of side effects.</p>
        </div>
    </div>
</div>

<div class="container-fluid care ">
    <div class="row ">
        <div class="col-lg-12 col-md-12 col-sm-12 col-12 p-0 ">
            <img class="loc-sm " style="position: relative; " src="{% static 'web/images/suscribe.png' %} "
                width="100% " alt=" ">
            <div class="col-lg-6 col-md-12 col-sm-12 col-12 locate locates ">
                <p>Stay in Touch with us</p>
                <p class="mb-3 ">Know more about <span class="ayt ">Ayucare</span> </p>


                <form action="{% url 'web:email' %}" method="POST" class="ajax reload">
                    {% csrf_token %}
                    {{ email_form.email }}
                    <button type="submit" class="btn read mt-2">Subscribe</button>

                </form>

            </div>
        </div>
    </div>
</div>
{% endblock %}

templates/web/test.html
<div id="showscrl" class="container doctor mb-5">
  {% for schedu in schedules %}
  <div class="row justify-content-center mb-4">

    <div class="col-lg-4 col-md-6 col-sm-12 col-12 mb-4">

      <h4 style="text-decoration: underline;">Doctor Details</h4>

      <h5>{{schedu.doctor.name}}</h5>
      <h6>Reg No : {{schedu.doctor.register_number}}</h6>
      <h6>{{schedu.doctor.qualification}}</h6>
      <h6 style="font-weight: 600;">{{schedu.start_time}} - {{schedu.end_time}}</h6>


    </div>

    <div class="col-lg-4 col-md-6 col-sm-12 col-12">


      <div id="" class="">
        <h4 class=" " style="text-decoration: underline;">Branch informations</h4>
        <div class="row pl-3">

          <div class="col-lg-10 col-10 p-0">
            <p style="color: black; text-align: left;">
              <span style="font-weight: 600;"> {{branch.name}}</span>
              <br>{{branch.title}}<br> {{branch.location}}<br>{{branch.phone}}
            </p>
          </div>
        </div>

      </div>
    </div>

    <div class="col-12 text-center">
      {% if whatsappbtn %}
      <a target="blank" href="{{whatsappbtn}}"> <button style="background: #3f993c;" class="read check appoi mt-3"><i
            class="icofont-brand-whatsapp mr-3"></i>Sent Appointment</button> </a>
      {% else %}
      <a href="#" onclick="btnclickcon('{{schedu.id}}')"> <button class="read check appoi mt-3">Book Appoinment</button>
      </a>
      {% endif %}
    </div>




  </div>
  {% endfor %}
</div>


<div class="col-lg-4 posit-absl" id="branna">

  <div class="colr-bg">


    <form action="" method="POST" class="mb-0">
      {% csrf_token %}
      <div onclick="btnclickconn()" id="clo"><span class="closse iconify"
          data-icon="ant-design:close-circle-outlined"></span></div>
      <input required style="height: 40px;" class="form-control required" type="text" name="brname" id="brname"
        placeholder="Name"> <br>
      <input required style="height: 40px;" class="form-control required" type="text" name="brnumber" id="brnumber"
        placeholder="Number"> <br>
      <button type="submit" class="btn btn-danger">Submit</button>

      <input type="hidden" name="scheduleID" id="scheduleID">

    </form>
  </div>
</div>