ayurcare/urls.py
from django.contrib import admin
from django.urls import path,include
from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    path('admin/', admin.site.urls), 
    path('',include('web.urls',namespace='web')),
    path('official/',include('official.urls',namespace='official')),

    path('tinymce/', include('tinymce.urls')),

]+ static(settings.STATIC_URL, document_root=settings.STATIC_ROOT) + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)
admin.site.site_header = "Ayurcare Administration"
admin.site.site_title = "Ayurcare Admin Portal"
admin.site.index_title = "Welcome to Ayurcare Admin Portal"

web/urls.py
from django.urls import path
from . import views

app_name = 'web'

urlpatterns = [
    path('', views.index,name="index"),
    path('about/',views.about,name="about"),
    path('branch/',views.branch,name="branch"),
    path('contact/',views.contact,name="contact"),
    path('doctors/',views.doctors,name="doctors"),
    path('galleries/',views.galleries,name="gallery"),
    path('products/',views.products,name="products"), 
    path('book/<int:id>',views.book,name="book"), 

    path('branchmark/',views.branchmark,name="branchmark"),
    path('districtsr/',views.districtsr,name="districtsr"),

    path('branchbook/<int:id>/',views.branchbook,name="branchbook"),
    path('email/',views.email,name="email"),

]

templates/web/partials/footer.html
<!-- start footer -->
{% load static %}
<footer>
    <div class="container ">
        <div class="row pt-5 pb-3 ">

            <div class="mb-3 col-lg-3 col-md-12 col-sm-12 col-12 f1 ">
                <div class="row mb-5 flogo ">
                    <img height="60px" src="{% static 'web/images/ayucareft.svg' %}" alt="">
                </div>
                <div class="row mt-10 flocat ">
                    <div class=" input-group ">
                        <input type="text " class="form-control form-controll " placeholder="Locate us " aria-label="Locate us " aria-describedby="basic-addon2 ">
                        <div class="input-group-append ">
                            <span class="input-group-text input-group-textt " style="background-color:#3f993c; border-color: #3f993c; " id="basic-addon2 "><span class="iconify input-group-textt " data-icon="fluent:location-28-filled "></span></span>
                        </div>
                    </div>
                </div>
            </div>
            <div class="mb-3 col-lg-3 col-md-6 col-sm-6 col-6 f2 use pl-3 ">
                <h5>Useful Links</h5>
                <ul>
                    <a href="{% url 'web:about' %}">
                        <li> <span> > </span>ABOUT US</li>
                    </a>
                    <a href="{% url 'web:products' %}">
                        <li> <span> > </span>PRODUCTS</li>
                    </a>
                    <a href="{% url 'web:gallery' %}">
                        <li> <span> > </span>GALLERY</li>
                    </a>
                    <a href="{% url 'web:contact' %}">
                        <li> <span> > </span>CONTACT US</li>
                    </a>
                    <a href="{% url 'web:doctors' %}">
                        <li> <span> > </span>OUR DOCTORS</li>
                    </a>

                </ul>
            </div>
            <div class="mb-3 col-lg-3 col-md-6 col-sm-6 col-6 f3 use ">
                <h5>Contact Us</h5>
                <ul>
                    <a href="mailto:info@ayucare.com ">
                        <li> <span class="iconify mr-2 cont " data-icon="ant-design:mail-twotone "></span>info@ayucare.com</li>
                    </a>
                    <a href="tel:+919876543210 ">
                        <li> <span class="iconify mr-2 cont " data-icon="cil:mobile "></span>(+91)9876543210</li>
                    </a>


                </ul>
            </div>
            <div class="mb-3 col-lg-3 col-md-12 col-sm-12 col-12 f4 follow ">

                Follow Us on 
                <a href="#" class="pl-3"><span class="iconify" data-icon="bi:facebook"></span> </a>
                <a href="#" class="pl-2"><span class="iconify" data-icon="bi:instagram"></span> </a>
                <a href="#" class="pl-2"><span class="iconify" data-icon="bi:twitter"></span> </a>
            </div>

        </div>
        <div class="row justify-content-center copy ">
            <p>Copyright © 2021. All rights reserved.Design by <a style="color: #3f993c; " href="https://gedexo.com/ " target="blank ">Gedexo</a> </p>
        </div>
    </div>
</footer>

templates/web/partials/header.html
{% load static %}
<!-- start Header -->

<nav class="site-navigationn" role="navigation">
    <div id="closse"><span class="closse iconify" data-icon="ant-design:close-circle-outlined"></span></div>
    <ul class="navigationn-ul p-5">
        <li><a href="/" class="nav-link {% if is_index %} active{% endif %}">HOME</a></li>
        <li><a href="{% url 'web:about' %}" class="nav-link {% if is_about %} active{% endif %}">ABOUT US</a></li>
        <li><a href="{% url 'web:products' %}" class="nav-link">PRODUCTS</a></li>
        <li><a href="{% url 'web:gallery' %}" class="nav-link">GALLERY</a></li>
        <li><a href="{% url 'web:contact' %}" class="nav-link">CONTACT US</a></li>
        <li><a href="{% url 'web:doctors' %}" class="nav-link">OUR DOCTORS</a></li>
    </ul>
</nav>
<div class="site-mobile-menu site-navbar-target">
    <div class="site-mobile-menu-header">
        <div class="site-mobile-menu-close mt-3">
            <span class="icon-close2 js-menu-toggle"></span>
        </div>
    </div>
    <div class="site-mobile-menu-body"></div>
</div>
<div class="top-bar" id="hre1">
    <div class="container">
        <div class="row justih">
            <div class="col-lg-4 col-4 dd-none">


                <a href="#" class="pr-2"><span class="iconify" data-icon="bi:twitter"></span> </a>
                <a href="#" class="pr-2"><span class="iconify" data-icon="bi:facebook"></span> </a>
                <a href="#" class=""><span class="iconify" data-icon="bi:instagram"></span> </a>

            </div>
            <div class="col-lg-4 col-4 text-center">
                <img height="60px" src="{% static 'web/images/ayucare.svg' %}" alt="">
            </div>
            <div class="col-lg-4 col-4 dd-none text-center">
                <a href="mailto:info@ayucare.com" class="mr-3">info@ayucare.com</a>
                <a href="tel:+919876543210" class=""><span class="d-none d-md-inline-block">(+91)9876543210</span></a>
            </div>
        </div>
    </div>
</div>
</div>
<header id="header" class="site-navbar js-sticky-header site-navbar-target" role="banner">
    <div class="container-fluid p-0">
        <div class="row position-relative">



            <div class="col-lg-8 col-8">
                <nav class="site-navigation" role="navigation">
                    <ul class="site-menu main-menu js-clone-nav d-none d-lg-block">
                        <li><a href="/" class="nav-link {% if is_index %} active {% endif %}">HOME</a></li>
                        <li><a onclick="setScroll('aboutpageId')" class="nav-link about-link {% if is_about %} active {% endif %}">ABOUT US</a></li>
                        <li><a href="{% url 'web:products' %}" class="nav-link {% if is_products %} active {% endif %}">PRODUCTS</a></li>
                        <li><a href="{% url 'web:gallery' %}" class="nav-link {% if is_gallery %} active {% endif %}">GALLERY</a></li>
                        <li><a href="{% url 'web:contact' %}" class="nav-link {% if is_contact %} active {% endif %}">CONTACT US</a></li>
                        <li><a href="{% url 'web:doctors' %}" class="nav-link {% if is_doctors %} active {% endif %}">OUR DOCTORS</a></li>
                    </ul>
                </nav>
            </div>
            
            <div class="col-lg-3 locate">
                <a href="{% url 'web:branch' %}" class="branch float-right">LOCATE BRANCH</a>
            </div>
            <div class="toggle-button d-inline-block d-lg-none"><a href="#" style="color: black;" class="site-menu-toggle py-5 js-menu-toggle text-black"><span class="iconify text-black" data-icon="gg:menu"></span></a>
            </div>
        </div>
    </div>
</header>

<!-- end Header -->